config/routes.rb
Rails.application.routes.draw do
  get 'home/buildings', to: 'home#buildings'
  get 'login/new', to: 'login#new'
  get 'home/points_of_interest'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'user#new'
  post '/users' => 'user#create'
  get '/settings' => 'user#show'
  post '/settings/update' => 'user#update'

  post '/show_poi' => 'home#show_poi'
  post '/hide_poi' => 'home#hide_poi'

  post '/show_south_study' => 'home#show_south_study'
  post '/hide_south_study' => 'home#hide_south_study'

  post '/show_query3' => 'home#show_query3'
  post '/hide_query3' => 'home#hide_query3'

  post '/show_food_and_study' => 'home#show_food_and_study'
  post '/hide_food_and_study' => 'home#hide_food_and_study'

  post '/show_north_museum' => 'home#show_north_museum'
  post '/hide_north_museum'=> 'home#hide_north_museum'

  post '/show_7am' => 'home#show_7am'
  post '/hide_7am' => 'home#hide_7am'

  post 'hide_best_places' => 'home#hide_best_places'
  post 'show_best_places' => 'home#show_best_places'

  get 'user_info' => 'user#user_info'


  get '/info' => 'home#building_info'

  post '/review/new/' => 'home#add_review'

  get '/user_image' => 'user#profile_picture'


  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  require 'json'
  require 'date'
  #before_filter :authorize

  def index
    @connection = ActiveRecord::Base.connection

    @zoom = 18




    if params[:show_poi] == "true"
      @objects = @connection.exec_query("SELECT m.id, g.longitude, g.latitude
                                         FROM map_object m, geo_point g, point_of_interest p
                                         WHERE g.object_id = m.id AND m.id = p.object_id
                                        ").rows
    elsif params[:show_south_study] == "true"
      @objects = @connection.exec_query("SELECT m.id, g.longitude, g.latitude FROM map_object m, building, geo_point g
                                        WHERE building.object_id = g.object_id
                                        AND longitude < 29.645
                                        AND study_space = 1
                                        AND computers = 1
                                        AND m.id = building.object_id").rows
    elsif params[:show_query3] == "true"
      @objects = @connection.exec_query("SELECT b.object_id, g.longitude, g.latitude FROM building b, reviews, geo_point g, restaurant r
                                        WHERE b.object_id = reviews.object_id
                                        AND r.object_id = b.object_id
                                        AND g.object_id = b.object_id
                                        AND reviews.rating > 3
                                        AND (SELECT count(*) FROM restaurant re WHERE re.object_id = b.object_id) > 2
                                        ORDER BY rating
                                        DESC").rows
    elsif params[:show_food_and_study] == "true"
      @objects = @connection.exec_query("SELECT g.object_id, g.longitude, g.latitude FROM geo_point g
                                         WHERE g.object_id
                                         IN (SELECT r.object_id FROM building b, map_object m, restaurant r
                                         WHERE m.id = b.object_id
                                         AND m.id = r.object_id)").rows
    elsif params[:show_north_museum] == "true"
      @objects = @connection.exec_query("SELECT m.id, p.longitude, p.latitude
                                         FROM building b, map_object m, geo_point p
                                         WHERE m.id = b.object_id
                                         AND m.id = p.object_id
                                         AND p.longitude >= 29.6449").rows

    elsif params[:show_7am]
      @objects = @connection.exec_query("SELECT g.object_id, g.longitude, g.latitude FROM geo_point g
                                         WHERE g.object_id
                                         IN (SELECT r.object_id FROM restaurant r, open_hours h
                                         WHERE h.day = 'Tuesday'
                                         AND r.id = h.rest_id
                                         AND h.open_time <= 700)").rows

    elsif params[:show_best_places]
      @objects = @connection.exec_query("SELECT m.id, g.longitude, g.latitude
                                         FROM map_object m, geo_point g
                                         WHERE m.id = g.object_id AND m.id IN
                                         (SELECT r.object_id
                                         FROM reviews r GROUP BY r.object_id
                                         HAVING AVG(r.rating) > 4
                                         )")

    else
      @objects = @connection.exec_query("SELECT m.id, g.longitude, g.latitude
                                         FROM map_object m, geo_point g, building b
                                         WHERE g.object_id = m.id
                                         AND b.object_id = m.id
                                        ").rows
    end


    @polylines = []
    @objects.each do |object|
      object_id = object[0]
      if @polylines[object_id].nil?
        @polylines[object_id] = Hash.new
        @polylines[object_id][:latlngs] = []
      end
      @polylines[object_id][:latlngs] << [object[1], object[2]]
      @polylines[object_id][:options] = { "clickable" => "true",
                                          "className" => object_id.to_s,
                                          "fill" => true ,
                                          "fillColor" => "#ff8080",
                                          "fillOpacity" => "0.5",
                                          "weight" => "3"
                                        }
    end

    @polylines = @polylines.reject { |e| e.to_s.empty? }
  end


  def building_info
    @connection = ActiveRecord::Base.connection
    @building = '{}' unless params[:object_id]

    @building = @connection.exec_query("SELECT * FROM building b, map_object m
                                        WHERE m.id = b.object_id
                                        AND m.id = #{params[:object_id]}").first

    @available_restaurants = @connection.exec_query("SELECT r.name, o.day, o.open_time, o.close_time
                                                    FROM restaurant r, open_hours o, map_object m
                                                    WHERE o.rest_id = r.id
                                                    AND r.object_id = #{params[:object_id]}
                                                    AND r.object_id = m.id
                                                    AND o.day = '#{Date.today.strftime("%A")}'")

    @reviews = @connection.exec_query("SELECT r.title, r.content, r.review_date, r.rating, u.email, u.first_name, u.last_name, u.img_path
                                       FROM reviews r, map_object m, users u
                                       WHERE m.id = r.object_id
                                       AND m.id = #{params[:object_id]}
                                       AND u.email = r.email
                                       ORDER BY r.review_date DESC")

    @avg_review = @connection.exec_query("SELECT AVG(rating) AS avg_review FROM reviews WHERE object_id = #{params[:object_id]}").first["avg_review"]

    @review_group = @connection.exec_query("SELECT rating, count(rating) AS count FROM reviews WHERE object_id = #{params[:object_id]} GROUP BY rating ORDER BY rating DESC")

    days =  { "Sunday" => 0, "Monday" => 1, "Tuesday" => 2, "Wednesday" => 3, "Thursday" => 4, "Friday" => 5, "Saturday" => 6 }

    @pops = @connection.exec_query("SELECT hour, popularity FROM pop_times WHERE object_id = #{params[:object_id]} AND day = #{days[Date.today.strftime("%A")]}")

    hash = { building: @building.to_hash, restaurants: @available_restaurants.to_hash, avg_review: @avg_review, review_group: @review_group.to_hash, reviews: @reviews.to_hash, pop_times: @pops.to_hash }
    render json: JSON.pretty_generate(hash)
  end

  def add_review
    authorize
    @connection = ActiveRecord::Base.connection
    @connection.execute("INSERT INTO reviews VALUES ('#{session[:email]}', #{params[:user][:object_id]}, '#{params[:user][:content]}', to_date('#{Time.now.strftime('%Y%m%d')}', 'yyyymmdd'), '#{params[:user][:title]}', #{params[:user][:rating]})")
    redirect_to '/'
  end


  def show_poi
    redirect_to controller: 'home', action: 'index', show_poi: true
  end

  def hide_poi
    redirect_to controller: 'home', action: 'index', show_poi: false
  end

  def show_south_study
    redirect_to controller: 'home', action: 'index', show_south_study: true
  end

  def hide_south_study
    redirect_to controller: 'home', action: 'index', show_south_study: false
  end

  def show_query3
    redirect_to controller: 'home', action: 'index', show_query3: true
  end

  def hide_query3
    redirect_to controller: 'home', action: 'index', show_query3: false
  end

  def show_food_and_study
    redirect_to controller: 'home', action: 'index', show_food_and_study: true
  end

  def hide_food_and_study
    redirect_to controller: 'home', action: 'index', show_food_and_study: false
  end

  def show_north_museum
    redirect_to controller: 'home', action: 'index', show_north_museum: true
  end

  def hide_north_museum
    redirect_to controller: 'home', action: 'index', show_north_museum: false
  end

  def show_7am
    redirect_to controller: 'home', action: 'index', show_7am: true
  end

  def hide_7am
    redirect_to controller: 'home', action: 'index', show_7am: false
  end

  def show_best_places
    redirect_to controller: 'home', action: 'index', show_best_places: true
  end

  def hide_best_places
    redirect_to controller: 'home', action: 'index', show_best_places: false
  end

end

app/helpers/home_helper.rb
module HomeHelper
  def show_prof_pic
    if @current_user
      path = @connection.exec_query("SELECT img_path FROM users
                                     WHERE email = '#{session[:email]}'")
    end
    "public/uploads/#{path}"
  end
end

app/views/home/_custom_queries.html.erb
<div class="custom-queries">
  <h4><i class="fa fa-filter" aria-hidden="true"></i>
    Useful Filters</h4>
<% if params[:show_poi] == 'false' || params[:show_poi].nil? %>
  <%= button_to "Show Points of Interest", show_poi_path, method: :post, params: { zoom: @zoom } %>
<% else %>
  <%= button_to "Hide Points of Interest", hide_poi_path, method: :post, params: { zoom: @zoom } %>
<% end %>

<% if params[:show_south_study] == 'false' || params[:show_south_study].nil? %>
  <%= button_to "Show me buildings on the south side of campus\n that have both computers and study space.", show_south_study_path, method: :post, params: { zoom: @zoom } %>
<% else %>
  <%= button_to "Hide Show me buildings on the south side of campus that have both computers and study space.", hide_south_study_path, method: :post, params: { zoom: @zoom } %>
<% end %>

<% if params[:show_query3] == 'false' || params[:show_query3].nil? %>
  <%= button_to "Show buildings with a rating over 3 and has more than 2 restaurants", show_query3_path, method: :post, params: { zoom: @zoom } %>
<% else %>
  <%= button_to "Hide buildings with a rating over 3 and has more than 2 restaurants", hide_query3_path, method: :post, params: { zoom: @zoom } %>
<% end %>

<% if params[:show_food_and_study] == 'false' || params[:show_food_and_study].nil? %>
  <%= button_to "Show me buildings that have food", show_food_and_study_path, method: :post, params: { zoom: @zoom } %>
<% else %>
  <%= button_to "Hide buildings that have food", hide_food_and_study_path, method: :post, params: { zoom: @zoom } %>
<% end %>

<% if params[:show_north_museum] == 'false' || params[:show_north_museum].nil? %>
  <%= button_to "Show me the buildings that are north of Museum Road", show_north_museum_path, method: :post, params: { zoom: @zoom } %>
<% else %>
  <%= button_to "Hide the buildings that are north of Museum Road", hide_north_museum_path, method: :post, params: { zoom: @zoom } %>
<% end %>

<% if params[:show_7am] == 'false' || params[:show_7a].nil? %>
  <%= button_to "Show me restaurants that are open at 7am or earlier on Tuesdays", show_7am_path, method: :post, params: { zoom: @zoom } %>
<% else %>
  <%= button_to "Hide restaurants that are open at 7am or earlier on Tuesdays", hide_7am_path, method: :post, params: { zoom: @zoom } %>
<% end %>


<% if params[:show_best_places] == 'false' || params[:show_best_places].nil? %>
  <%= button_to "Show me all the buildings with average rating greater than 4", show_7am_path, method: :post, params: { zoom: @zoom } %>
<% else %>
  <%= button_to "Hide the buildings with average rating greater than 4", hide_7am_path, method: :post, params: { zoom: @zoom } %>
<% end %>
</div>

app/views/home/_icon-stats.erb
<div id="icon-stats">
  <div class="stat-row">
    <div class="stats-col">
      <i class="fa fa-building" aria-hidden="true"></i>
      <p><span id="floors">6</span> floors</p>
    </div>
    <div class="stats-col">
      <i class="fa fa-plug" aria-hidden="true"></i>
      <p><span id="outlets">8</span> outlets</p>
    </div>
    <div id="studying" class="stats-col">
      <i class="fa fa-institution" aria-hidden="true"></i>
      <p>Studying</p>
    </div>
    <div id="computers" class="stats-col">
      <i class="fa fa-desktop" aria-hidden="true"></i>
      <p>Computers</p>
    </div>
  </div>
</div>

app/views/home/_logged_in_index.html.erb
<!-- Hi, you are logged in! -->

<!-- <h1>MapDat</h1>
<p>Find me in app/views/leaflet/index.html.erb</p> -->

<!-- <div id="mapid"></div> -->
<div class="container">
  <%= render "sidebar" %>
    <div id="sideBar-right" class="clicked-right">
    <div class="top-row">
      <h3>Hey there, <span id="user-name">Vincent</span></h3>
      <%= button_to "About", method: :get%>
      <%= button_to "Logout", logout_path, method: :get%>
      <%= button_to "Settings", settings_path, method: :get%>
    </div>
    <%= render 'custom_queries' %>
  </div>

  <button type="button" class="account-btn account-clicked" name="button">
    <!-- <img src="" alt=""> -->
  </button>
</div>

<script>

  $(".render-review-form").show();

  $(".render-review-form").click(function(){
    $(".full-screen-holder").show();
  });

  function fillUserSidebar(){
   $.getJSON("/user_info", function(user){
     $("#user-name").text(user.first_name);
     $(".account-btn").css("background-image", "url(/assets/" + user.img_path + ")");
   });
  };

  $(document).ready(function(){
    fillUserSidebar();
    map.zoomControl.setPosition('bottomright');
   });

</script>

app/views/home/_logged_out_index.html.erb
<!-- Hi, you are not logged in! -->

<!-- <h1>MapDat</h1>
<p>Find me in app/views/leaflet/index.html.erb</p> -->

<!-- <div id="mapid"></div> -->

<div class="container">
  <%= render "sidebar" %>
  <a href="/signup"><button type="button" class="btn signup-btn" name="button">Sign Up</button></a>
  <button type="button" class="btn login-btn" name="button">Log In</button>
  <div class="login-container login-clicked-container">
    <%= render "sessions/form" %>
  </div>
</div>

<script>

$(document).ready(function(){


      $('#leftside-btn').click(function(){
        if( $('#sideBar-left').hasClass('clicked-left')){
          $(".fa-chevron-right").addClass('clicked-chevron');
          $('#sideBar-left').removeClass('clicked-left');
        } else {
          $(".fa-chevron-right").removeClass('clicked-chevron');
          $('#sideBar-left').addClass('clicked-left');
        }
      });

      $('.login-btn').click(function(){
        $('.login-btn').toggleClass('login-clicked');
        $('.login-container').toggleClass('login-clicked-container');
        $('input').toggleClass('login-clicked-form');
        $('h4').toggleClass('login-clicked-h4');
        $('.signup-btn').toggleClass('login-clicked-signup');
      });

      map.zoomControl.setPosition('bottomright');

 });

</script>

app/views/home/_popular-times.erb
<div id="popular">
  <div class="popular-times-row">
    <div class="popular-container">
      <div class="hour" id="0" style="height: 2%;"></div>
      <div class="hour" id="1" style="height: 2%;"></div>
      <div class="hour" id="2" style="height: 10%;"></div>
      <div class="hour" id="3" style="height: 20%;"></div>
      <div class="hour" id="4" style="height: 30%;"></div>
      <div class="hour" id="5" style="height: 45%;"></div>
      <div class="hour" id="6" style="height: 50%;"></div>
      <div class="hour" id="7" style="height: 65%;"></div>
      <div class="hour" id="8" style="height: 75%;"></div>
      <div class="hour" id="9" style="height: 85%;"></div>
      <div class="hour" id="10" style="height: 95%;"></div>
      <div class="hour" id="11" style="height: 90%;"></div>
      <div class="hour" id="12" style="height: 86%;"></div>
      <div class="hour" id="13" style="height: 50%;"></div>
      <div class="hour" id="14" style="height: 12%;"></div>
    </div>
    <div class="time-row">
      <div class="time">
        <p>6am</p>
      </div>
      <div class="time">
        <p>9am</p>
      </div>
      <div class="time">
        <p>12pm</p>
      </div>
      <div class="time">
        <p>3pm</p>
      </div>
      <div class="time">
        <p>6pm</p>
      </div>
    </div>
  </div>
</div>

app/views/home/_rating.erb
<div id="review-row">
  <p id="avg-review" class="review">4.6</p>
  <div class="avg-review-stars">
    <i class="fa fa-star star1" aria-hidden="true"></i>
    <i class="fa fa-star star2" aria-hidden="true"></i>
    <i class="fa fa-star star3" aria-hidden="true"></i>
    <i class="fa fa-star star4" aria-hidden="true"></i>
    <i class="fa fa-star star5" aria-hidden="true"></i>
  </div>
  <div class="circle-divider"></div>
  <p class="review total">12 reviews</p>
</div>

app/views/home/_restaurant.erb
<div id="restaurant">
  <div class="open">
    <i class="fa fa-birthday-cake" aria-hidden="true"></i>
    <h2><span id="restaurant-count">0</span> restaurants open</h2>
  </div>
  <div id="new-restaurant"></div>
</div>

app/views/home/_review_form.html.erb
<div class="full-screen-holder" style="display:none">
  <div class="create-review">
    <div class="header-review">
      <h5>Rate & Review</h5>
    </div>
    <div class="review-body">

      <%= form_for :user, url: '/review/new' do |f| %>
      <%= f.radio_button :rating, 1 %>
      <i class="fa fa-star star1" aria-hidden="true"></i> 1

      <%= f.radio_button :rating, 2 %>
      <i class="fa fa-star" aria-hidden="true"></i> 2

      <%= f.radio_button :rating, 3 %>
      <i class="fa fa-star" aria-hidden="true"></i> 3

      <%= f.radio_button :rating, 4 %>
      <i class="fa fa-star" aria-hidden="true"></i> 4

      <%= f.radio_button :rating, 5 %>
      <i class="fa fa-star" aria-hidden="true"></i> 5

      <!-- Review Title: <%= f.text_field :title %> -->
      <%= f.text_area :content %>
      <div id="divCheckbox" style="display: none;">
        <%= f.text_area :object_id, :id => "review_obj" %>
      </div>
      <div class="submit-button">
        <%= f.submit "Submit" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/home/_reviews.erb
<div id="reviews">
  <div class="avg-rating">
    <%= render "rating" %>
  </div>
  <div class="total-ratings">
    <div class="rating-row">
      <p>1</p>
      <i class="fa fa-star" aria-hidden="true"></i>
      <div id="" class="percentage"></div>
      <p class="total-count">20</p>
    </div>
    <div class="rating-row">
      <p>2</p>
      <i class="fa fa-star" aria-hidden="true"></i>
      <div class="percentage" style="width: 40%;"></div>
      <p class="total-count">20</p>
    </div>
    <div class="rating-row">
      <p>3</p>
      <i class="fa fa-star" aria-hidden="true"></i>
      <div class="percentage" style="width: 30%;"></div>
      <p class="total-count">20</p>
    </div>
    <div class="rating-row">
      <p>4</p>
      <i class="fa fa-star" aria-hidden="true"></i>
      <div class="percentage" style="width: 10%;"></div>
      <p class="total-count">20</p>
    </div>
    <div class="rating-row">
      <p>5</p>
      <i class="fa fa-star" aria-hidden="true"></i>
      <div class="percentage" style="width: 10%;"></div>
      <p class="total-count">2</p>
    </div>
  </div>
  <div class="divider"></div>
  <div class="custom-queries render-review-form" style="display:none">
    <input type="submit" value="Submit Review">
    <%= render 'review_form' %>
  </div>
  <div class="indv-reviews-container">
    <div class="indv-review"></div>
  </div>
</div>

app/views/home/_sidebar.erb
<%= stylesheet_link_tag "sidebar" %>

<div id="sideBar-left" class="clicked-left">
<!-- <div id="sideBar-left" class="clicked-left"> -->
  <!-- <div class="searchBar">
    <div id="search-input">
        <div class="input-group col-md-12">
            <input type="text" class="form-control input-lg" placeholder="Search" />
            <span class="input-group-btn">
                <button class="btn-info btn-lg" type="button">
                  <i class="fa fa-search" aria-hidden="true"></i>
                </button>
            </span>
        </div>
    </div>
  </div> -->
  <div class="sideBar-tab">
    <button class="btn-info btn-lg" id="leftside-btn" type="button">
      <i class="fa fa-chevron-right" aria-hidden="true"></i>
    </button>
  </div>
  <div class="sideBar-body">
    <div class="cover">
      <img src="http://static.panoramio.com/photos/large/53625922.jpg" alt="" />
    </div>
    <div class="title">
      <img class="title-thumb" src="http://static.panoramio.com/photos/large/53625922.jpg" alt="" />
      <h3 class="title-h3">Marston Science Library</h3>
      <%= render "rating" %>
    </div>
    <div class="sideBar-white">
      <div id="description">
        <p>The University of Florida Marston Science Library
          is the science and engineering library of the University
          of Florida located in Gainesville, Florida, and is
          administered by the university's George A. Smathers
          Libraries system</p>
      </div>
      <div class="divider"></div>
      <%= render "popular-times" %>
      <div class="divider"></div>
      <%= render "icon-stats" %>
      <div class="divider"></div>
      <%= render "restaurant" %>
      <div class="divider"></div>
      <%= render "reviews" %>
    </div>
  </div>
</div>

<script type="text/javascript">
  var wrap = $(".sideBar-body");
  wrap.on("scroll", function(e) {

    if (this.scrollTop > 282) {
      $(".title").addClass("title-locked");
      $("#review-row").addClass("title-locked-review");
      $(".sideBar-white").addClass("title-locked-white");
      $(".title-thumb").addClass("title-thumb-locked");
      $(".title-h3").addClass("title-h3-locked");
    } else {
      $(".title").removeClass("title-locked");
      $("#review-row").removeClass("title-locked-review");
      $(".sideBar-white").removeClass("title-locked-white");
      $(".title-thumb").removeClass("title-thumb-locked");
      $(".title-h3").removeClass("title-h3-locked");
    }
  });
</script>